site_name: Zcord
site_description: A thin Discord API wrapper written in Python
site_url: https://zcord.readthedocs.io/

repo_name: thqnhz/zcord
repo_url: https://github.com/thqnhz/zcord
copyright: Copyright &copy; 2026 ZyubyL

theme:
  font:
    text: Inter
    code: Jetbrains Mono
  name: materialx
  palette:
    scheme: slate
  locale: en
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.prune
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  logo: assets/zcord_original.png
  favicon: assets/zcord_original.png

extra:
  homepage: https://zcord.readthedocs.io

plugins:
  - search:
      enabled: true
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_signature_annotations: true
            show_root_heading: true
            show_bases: false
            show_root_members_full_path: false
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: false
            show_labels: false
            modernize_annotations: true
            members_order: source
            docstring_style: google
          inventories:
            - https://docs.python.org/3/objects.inv

markdown_extensions:
  - toc:
      toc_depth: 4
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - API Reference: api.md
